### ISSUE TITLE
freeze + blackscreen when tryin to switch the room

### ISSUE THREAD

**Issue by NotHazed** [billsonnn/nitro-react#125]
sometimes when you wanna go to another room, 1 side of the walls turn black and after 30 seconds you get a blackscreen and need to reload the client.

screenshot: 
![image](https://user-images.githubusercontent.com/22569203/211099738-e53732bd-77b3-4fd4-92a0-83a57d2a7026.png)

on the right side you can see the wall turn to black, everything is freezed and after 30sec the whole screen turns black, you need to reload

from chrome console:
vendor-ea65b227.js:352 Uncaught TypeError: Cannot read properties of null (reading 'resolution')
    at e.bind (vendor-ea65b227.js:352:10237)
    at t.render (vendor-ea65b227.js:422:24708)
    at HE.writeToRenderTexture (nitro-renderer-59421089.js:103:1527)
    at HE.clearRenderTexture (nitro-renderer-59421089.js:103:816)
    at oe.render (nitro-renderer-59421089.js:106:711148)
    at Nh.render (nitro-renderer-59421089.js:106:714821)
    at Mh.render (nitro-renderer-59421089.js:106:696805)
    at yG.render (nitro-renderer-59421089.js:106:699870)
    at Di.render (nitro-renderer-59421089.js:106:701693)
    at UG.render (nitro-renderer-59421089.js:106:724416)

**Comment by NotHazed** [comment]
![image](https://user-images.githubusercontent.com/22569203/211171466-a7456a09-2e36-421d-94c2-29ad69d893b7.png)


Uncaught TypeError: Cannot read properties of null (reading 'resolution')
    at e.bind (vendor-ea65b227.js:352:10237)
    at t.render (vendor-ea65b227.js:422:24708)
    at HE.writeToRenderTexture (nitro-renderer-59421089.js:103:1527)
    at HE.clearRenderTexture (nitro-renderer-59421089.js:103:816)
    at oe.render (nitro-renderer-59421089.js:106:711148)
    at Nh.render (nitro-renderer-59421089.js:106:714821)
    at Mh.render (nitro-renderer-59421089.js:106:696805)
    at yG.render (nitro-renderer-59421089.js:106:699870)
    at Di.render (nitro-renderer-59421089.js:106:701693)
    at UG.render (nitro-renderer-59421089.js:106:724416)
131Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: <URL>
3vendor-ea65b227.js:352 Uncaught TypeError: Cannot read properties of null (reading 'resolution')
    at e.bind (vendor-ea65b227.js:352:10237)
    at t.render (vendor-ea65b227.js:422:24708)
    at HE.writeToRenderTexture (nitro-renderer-59421089.js:103:1527)
    at HE.clearRenderTexture (nitro-renderer-59421089.js:103:816)
    at oe.render (nitro-renderer-59421089.js:106:711148)
    at Nh.render (nitro-renderer-59421089.js:106:714821)
    at Mh.render (nitro-renderer-59421089.js:106:696805)
    at yG.render (nitro-renderer-59421089.js:106:699870)
    at Di.render (nitro-renderer-59421089.js:106:701693)
    at UG.render (nitro-renderer-59421089.js:106:724416)

**Comment by NotHazed** [comment]
my pic above was uploaded as png
here is the gif version: https://i.imgur.com/i4bvQzo.gif

**Comment by dank074** [comment]
Known issue. Currently being worked on

**Comment by billsonnn** [comment]
This should now be fixed
