### ISSUE TITLE
[URGENT ISSUE] Nitro is freezing

### ISSUE THREAD

**Issue by NotHazed** [billsonnn/nitro-react#134]
Since the latest updates there are performance problems with Nitro. The badge inventory works again, but the badges first load as a square and after 5-6 seconds they are displayed in full size.

Sometimes when you switch rooms or open your inventory, the client freezes. You can see what the other users are doing and chatting, but you can't click anything anymore and have to restart. Please fix this bug, it's been like this since the Landscape Update.

GIF: https://imgur.com/FngaA9s

**Comment by NotHazed** [comment]
Console Error:
Uncaught TypeError: Cannot read properties of null (reading 'width')
    at t.get (vendor-56d266b8.js:17:56015)
    at cu.clearAndFillRenderTexture (nitro-renderer-87a406ed.js:103:1799)
    at cu.createAndFillRenderTexture (nitro-renderer-87a406ed.js:103:1503)
    at OB.render (nitro-renderer-87a406ed.js:106:708333)
    at to.render (nitro-renderer-87a406ed.js:106:732584)
    at MB.render (nitro-renderer-87a406ed.js:106:733141)
    at ks.getTexture (nitro-renderer-87a406ed.js:106:742087)
    at ks.update (nitro-renderer-87a406ed.js:106:745443)
    at Kt.updatePlanes (nitro-renderer-87a406ed.js:106:761847)
    at Kt.update (nitro-renderer-87a406ed.js:106:754769)

**Comment by dank074** [comment]
pull latest nitro react
